[toolchain]
# Stable
channel = "1.87.0" # rustc 1.87.0 (17067e9ac 2025-05-09)
components = ["cargo", "clippy", "rustc", "rustfmt", "rust-src", "rust-docs"]
profile = "minimal"
targets = ["wasm32-unknown-unknown"]