[package]
name = "pallet-evm-precompile-dispatch"
version = "2.0.0-dev"
license = "Apache-2.0"
description = "DISPATCH precompiles for EVM pallet."
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[dependencies]
scale-codec = { workspace = true, default-features = false }
# Substrate
frame-support = { workspace = true, default-features = false }
sp-runtime = { workspace = true, default-features = false }
# Frontier
fp-evm = { workspace = true, default-features = false }
pallet-evm = { workspace = true, default-features = false }

[dev-dependencies]
scale-info = { workspace = true, default-features = false }
# Substrate
frame-system = { workspace = true, features = ["default"], default-features = false }
pallet-balances = { workspace = true, features = ["default", "insecure_zero_ed"], default-features = false }
pallet-timestamp = { workspace = true, features = ["default"], default-features = false }
pallet-utility = { workspace = true, features = ["default"], default-features = false }
sp-core = { workspace = true, features = ["default"], default-features = false }
sp-io = { workspace = true, features = ["default"], default-features = false }
sp-runtime = { workspace = true, features = ["default"], default-features = false }

[features]
default = ["std"]
std = [
	"scale-codec/std",
	# Substrate
	"frame-support/std",
	"sp-runtime/std",
	# Frontier
	"fp-evm/std",
	"pallet-evm/std",
]
