[package]
name = "pallet-evm-precompile-bw6761"
version = "1.0.0-dev"
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }

[dependencies]
# Arkworks
ark-bw6-761 = { workspace = true, default-features = false }
ark-ec = { workspace = true, default-features = false }
ark-ff = { workspace = true, default-features = false }
ark-std = { workspace = true, default-features = false }

# Frontier
fp-evm = { workspace = true, default-features = false }

[dev-dependencies]
# Frontier
pallet-evm-test-vector-support = { workspace = true, default-features = false }

[features]
default = ["std"]
std = [
	# Arkworks
	"ark-bw6-761/std",
	"ark-ec/std",
	"ark-ff/std",
	"ark-std/std",

	# Frontier
	"fp-evm/std",
]
