name: Editorconfig

on:
  push:
    branches:
      - master
      - 'polkadot-v**'
      - 'frontier-stable**-otf-patches'
  pull_request:

jobs:
  check:
    name: 'Check editorconfig'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker
